version: "3"
services:
  postal:
    image: catdeployed/postal:ubuntu
    command: run
    ports:
      - 127.0.0.1:25:25
    depends_on:
      - "mysql"
      - "rabbitmq"
    volumes:
      - static_assets:/opt/postal/public
      - ./data/postal/assets:/opt/postal/public/assets
      - ./src/templates/:/templates
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=postal
  mysql:
    image: mariadb:10
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=/postal
  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - postal
    depends_on:
      - postal
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_assets:/opt/postal/public:ro
      - ./data/postal/assets:/opt/postal/public/assets:ro
volumes:
  static_assets:

